# Generated by Django 3.1.7 on 2021-03-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210331_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='product',
        ),
    ]
